apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: my-app
        image: gassermohsen/app:v1
        envFrom:
        - configMapRef:
            name: python-redis-config
        ports:
        - containerPort: 80
 
